# on:
#   push:
#     branches:
#       - adf_publish

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Azure login
#         uses: azure/login@v1
#         with:
#           creds: |
#             {
#               "clientId": "${{ secrets.CLIENT_ID }}",
#               "clientSecret": "${{ secrets.CLIENT_SECRET }}",
#               "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}",
#               "tenantId": "${{ secrets.TENANT_ID }}"
#             }

    #   - name: Set up Azure PowerShell
    #     run: |
    #       Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber -RequiredVersion $env:PSAzureVersion
    #       Import-Module Az
    #       $psCredential = Get-Credential -UserName $env:PSAzureApplicationId -Password $env:PSAzureServicePrincipalSecret
    #       Connect-AzAccount -ServicePrincipal -Credential $psCredential -Tenant $env:PSAzureTenant -ApplicationId $env:PSAzureApplicationId
    #     shell: pwsh
    #     env:
    #       PSAzureTenant: ${{ secrets.TENANT_ID }}
    #       PSAzureApplicationId: ${{ secrets.CLIENT_ID }}
    #       PSAzureServicePrincipalSecret: ${{ secrets.CLIENT_SECRET }}
    #       azPSVersion: "latest"  # Specify the desired version here

    #   - name: Get latest code
    #     uses: actions/checkout@v2

    #   - name: Azure PowerShell Script
    #     run: |
    #       .\cicdscript.ps1 -armTemplate "./devadfbytej/ARMTemplateForFactory.json" -ResourceGroupName "Tej_RG" -DataFactoryName "devadfbytej" -predeployment $true -deleteDeployment $false
    #     shell: pwsh


    #   - name: Run Azure PowerShell Script File
    #     uses: azure/powershell@v1
    #     with:
    #         inlineScript:  .\cicdscript.ps1 -armTemplate "./devadfbytej/ARMTemplateForFactory.json" -ResourceGroupName "Tej_RG" -DataFactoryName "devadfbytej" -predeployment $true -deleteDeployment $false
    #         azPSVersion: "latest"



on:
  push:
    branches:
      - adf_publish

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.CLIENT_ID }}",
              "clientSecret": "${{ secrets.CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.TENANT_ID }}"
            }
      - name: Set up Azure PowerShell
        run: |
            Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber -RequiredVersion $env:PSAzureVersion
            Import-Module Az
            Connect-AzAccount -UseDeviceAuthentication
            Set-AzContext -SubscriptionId 'cd80669d-c886-455a-b108-8299fac678e3'
        shell: pwsh
        env:
            PSAzureVersion: '2.6.0'
   

      - name: Get latest code
        uses: actions/checkout@v2

      - name: Run Azure PowerShell Script File
        uses: azure/powershell@v1
        with:
            inlineScript:  .\cicdscript.ps1 -armTemplate "./devadfbytej/ARMTemplateForFactory.json" -ResourceGroupName "Tej_RG" -DataFactoryName "devadfbytej" -predeployment $true -deleteDeployment $false
            azPSVersion: "latest"
    #   - name: Set up Azure PowerShell
    #     run: |
    #       Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber -RequiredVersion $env:PSAzureVersion
    #       Import-Module Az
    #       $azureAplicationId ="${{ secrets.CLIENT_ID }}"
    #       $azureTenantId= "${{ secrets.TENANT_ID }}"
    #       $azurePassword = ConvertTo-SecureString "${{ secrets.CLIENT_SECRET }}" -AsPlainText -Force
    #       $psCred = New-Object System.Management.Automation.PSCredential($azureAplicationId , $azurePassword)
    #       Connect-AzAccount -ServicePrincipal -Credential $psCred -Tenant $azureTenantId -ApplicationId $azureAplicationId
    #     shell: pwsh
    #     env:
    #       PSAzureTenant: ${{ secrets.TENANT_ID }}
    #       PSAzureApplicationId: ${{ secrets.CLIENT_ID }}
    #       PSAzureServicePrincipalSecret: ${{ secrets.CLIENT_SECRET }}
    #       PSAzureVersion: "2.6.0"  # Specify the desired version here