on:
  push:
    branches:
      - adf_publish

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.CLIENT_ID }}",
              "clientSecret": "${{ secrets.CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.TENANT_ID }}"
            }

      - name: Get latest code
        uses: actions/checkout@v2

      - name: Azure PowerShell Script
        run: |
          Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber
          Import-Module Az
          Connect-AzAccount -ServicePrincipal -Credential $PSAzureCredential -Tenant $PSAzureTenant -ApplicationId $PSAzureApplicationId
          .\cicd (1).ps1 -armTemplate "$(System.DefaultWorkingDirectory)/_ADF/devadfbytej/ARMTemplateForFactory.json" -ResourceGroupName "Tej_RG" -DataFactoryName "devadfbytej" -predeployment $true -deleteDeployment $false
        shell: pwsh
        env:
          PSAzureCredential: ${{ secrets.CLIENT_ID }}
          PSAzureTenant: ${{ secrets.TENANT_ID }}
          PSAzureApplicationId: ${{ secrets.CLIENT_ID }}
          PSAzureServicePrincipalSecret: ${{ secrets.CLIENT_SECRET }}
